// Compiles cleanly against a real UE 5.4.4 editor (verified
// 2026-09-15). Real mesh dispatch verified end-to-end and visually
// (verified 2026-09-16 -- see KNOWN_GAPS_AND_ISSUES.md's
// "[RESOLVED] LoadProceduralScenario now dispatches real mesh
// sections" entry): a real 840-mesh scenario generated by this repo's
// own Python pipeline, sent over the real WebSocket JSON-RPC bridge
// (USyntheticDataGenRpcSubsystem) to a live PIE session, produced real
// visible geometry in the viewport, not just a `true` RPC response.
//
// UE5-side counterpart to src/ue5/backend.py: receives the JSON payload
// that backend.py's UE5Backend.load_scenario() sends over the
// LoadProceduralScenario JSON-RPC method, and dispatches one
// UScenarioMeshBuilder::BuildMeshSection call per entry in the
// payload's "meshes" array, plus (as of City Sample asset integration
// Phase 1) one UVehicleActorSpawner::SpawnVehicle call per
// category:"vehicle" entry in the payload's "assets" array. Traffic
// controller initialization and streaming/culling (MASTER_PROMPT
// Section 3.5's remaining "Procedural Meshes"/"Traffic Network" bullets
// for this phase) are still not implemented -- there's no
// traffic-controller actor class yet to initialize, and
// streaming/culling needs profiling against a real, populated level.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "ProceduralScenarioLoader.generated.h"

/**
 * Parses and loads one generated scenario (as JSON from the Python-side
 * orchestration layer) into the current UE5 level.
 *
 * Each call fully replaces whatever scenario was loaded previously
 * (ClearPreviousScenario) -- safe to call repeatedly against one
 * running session, e.g. to cycle through several procedurally
 * generated city layouts live without restarting the editor/game.
 */
UCLASS()
class SYNTHETICDATAGEN_API AProceduralScenarioLoader final : public AActor
{
	GENERATED_BODY()

public:
	AProceduralScenarioLoader();

	/**
	 * Parses ScenarioJson (the payload UE5Backend.load_scenario() sends)
	 * and builds one mesh section per entry in its "meshes" array, plus
	 * spawns one vehicle actor per category:"vehicle" entry in its
	 * "assets" array.
	 *
	 * @param ScenarioJson  UTF-8 JSON with top-level "meshes" and
	 *        "assets" arrays. Each "meshes" entry has "vertices"
	 *        ([[x,y,z], ...]), "triangles" (flat int list), "uvs"
	 *        ([[u,v], ...]), and "material" (string), matching
	 *        src/procedural/mesh_factory.py's Mesh dataclass
	 *        field-for-field. Each "assets" entry has "category",
	 *        "asset_path", "position" ([x,y,z]), "rotation_rad", and
	 *        "id", matching scenario_serializer.py's asset-entry
	 *        schema -- only "category": "vehicle" is spawned so far;
	 *        "prop"/"hero_building" entries are skipped, not fatal,
	 *        until later City Sample integration phases add them.
	 *        Missing "meshes"/"assets" fields are each treated as a
	 *        valid, empty scenario, not an error. Traffic-network data
	 *        (nodes/edges/lanes/traffic) is not yet part of this
	 *        schema -- see KNOWN_GAPS_AND_ISSUES.md.
	 * @return true if the payload was well-formed JSON (individual
	 *         malformed mesh/asset entries are skipped and logged, not
	 *         fatal).
	 *
	 * Also repositions the local player's pawn to overlook the real
	 * bounds of whatever was just built (see this .cpp's
	 * RepositionOverviewCamera) -- a real fix, not a nicety: the
	 * level's own default PlayerStart has no relationship to a
	 * generated scenario's coordinates, confirmed via a real screenshot
	 * showing the camera looking at the current level's own default
	 * geometry instead of the generated city. See
	 * KNOWN_GAPS_AND_ISSUES.md.
	 */
	UFUNCTION(BlueprintCallable, Category = "SyntheticDataGen")
	bool LoadProceduralScenario(const FString& ScenarioJson);

private:
	/**
	 * Destroys every mesh section component and spawned vehicle actor
	 * left over from a previous LoadProceduralScenario call, so each
	 * call fully replaces the scene instead of accumulating overlapping
	 * geometry on top of it. Called at the start of
	 * LoadProceduralScenario, once the incoming JSON is confirmed
	 * well-formed (so a malformed payload never wipes an already-loaded
	 * scenario).
	 */
	void ClearPreviousScenario();

	/**
	 * Applies the optional top-level "environment" object of a scenario
	 * payload to the current level: hides the engine template's terrain,
	 * retunes the sun, height fog and adds an unbound post-process volume
	 * (grade/exposure). Every field is optional; values are the ones
	 * measured in Epic's City Sample levels (see KNOWN_GAPS_AND_ISSUES.md).
	 * The post-process volume is tracked in SpawnedAssetActors so each
	 * LoadProceduralScenario call replaces it instead of stacking volumes.
	 */
	void ApplyEnvironment(const TSharedPtr<FJsonObject>& Environment);

	/** Vehicles spawned by the most recent LoadProceduralScenario call
	 * (mesh sections are components of this actor and don't need
	 * separate tracking; spawned vehicles are independent actors in the
	 * world and do). */
	UPROPERTY()
	TArray<TObjectPtr<AActor>> SpawnedAssetActors;
};
