// Compiles cleanly against a real UE 5.4.4 editor (verified
// 2026-09-15). Real mesh dispatch verified end-to-end and visually
// (verified 2026-09-16 -- see KNOWN_GAPS_AND_ISSUES.md's
// "[RESOLVED] LoadProceduralScenario now dispatches real mesh
// sections" entry): a real 840-mesh scenario generated by this repo's
// own Python pipeline, sent over the real WebSocket JSON-RPC bridge
// (USyntheticDataGenRpcSubsystem) to a live PIE session, produced real
// visible geometry in the viewport, not just a `true` RPC response.
//
// UE5-side counterpart to src/ue5/backend.py: receives the JSON payload
// that backend.py's UE5Backend.load_scenario() sends over the
// LoadProceduralScenario JSON-RPC method, and dispatches one
// UScenarioMeshBuilder::BuildMeshSection call per entry in the
// payload's "meshes" array, plus (as of City Sample asset integration
// Phase 1) one UVehicleActorSpawner::SpawnVehicle call per
// category:"vehicle" entry in the payload's "assets" array. Traffic
// controller initialization and streaming/culling (MASTER_PROMPT
// Section 3.5's remaining "Procedural Meshes"/"Traffic Network" bullets
// for this phase) are still not implemented -- there's no
// traffic-controller actor class yet to initialize, and
// streaming/culling needs profiling against a real, populated level.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "ProceduralScenarioLoader.generated.h"

class ULevel;

/**
 * Parses and loads one generated scenario (as JSON from the Python-side
 * orchestration layer) into the current UE5 level.
 *
 * Each call fully replaces whatever scenario was loaded previously
 * (ClearPreviousScenario) -- safe to call repeatedly against one
 * running session, e.g. to cycle through several procedurally
 * generated city layouts live without restarting the editor/game.
 */
UCLASS()
class SYNTHETICDATAGEN_API AProceduralScenarioLoader final : public AActor
{
	GENERATED_BODY()

public:
	AProceduralScenarioLoader();

	/**
	 * Parses ScenarioJson (the payload UE5Backend.load_scenario() sends)
	 * and builds one mesh section per entry in its "meshes" array, plus
	 * spawns one vehicle actor per category:"vehicle" entry in its
	 * "assets" array.
	 *
	 * @param ScenarioJson  UTF-8 JSON with top-level "meshes" and
	 *        "assets" arrays. Each "meshes" entry has "vertices"
	 *        ([[x,y,z], ...]), "triangles" (flat int list), "uvs"
	 *        ([[u,v], ...]), and "material" (string), matching
	 *        src/procedural/mesh_factory.py's Mesh dataclass
	 *        field-for-field. Each "assets" entry has "category",
	 *        "asset_path", "position" ([x,y,z]), "rotation_rad", and
	 *        "id", matching scenario_serializer.py's asset-entry
	 *        schema -- only "category": "vehicle" is spawned so far;
	 *        "prop"/"hero_building" entries are skipped, not fatal,
	 *        until later City Sample integration phases add them.
	 *        Missing "meshes"/"assets" fields are each treated as a
	 *        valid, empty scenario, not an error. Traffic-network data
	 *        (nodes/edges/lanes/traffic) is not yet part of this
	 *        schema -- see KNOWN_GAPS_AND_ISSUES.md.
	 * @return true if the payload was well-formed JSON (individual
	 *         malformed mesh/asset entries are skipped and logged, not
	 *         fatal).
	 *
	 * Also repositions the local player's pawn to overlook the real
	 * bounds of whatever was just built (see this .cpp's
	 * RepositionOverviewCamera) -- a real fix, not a nicety: the
	 * level's own default PlayerStart has no relationship to a
	 * generated scenario's coordinates, confirmed via a real screenshot
	 * showing the camera looking at the current level's own default
	 * geometry instead of the generated city. See
	 * KNOWN_GAPS_AND_ISSUES.md.
	 */
	UFUNCTION(BlueprintCallable, Category = "SyntheticDataGen")
	bool LoadProceduralScenario(const FString& ScenarioJson);

private:
	/**
	 * Destroys every mesh section component and spawned vehicle actor
	 * left over from a previous LoadProceduralScenario call, so each
	 * call fully replaces the scene instead of accumulating overlapping
	 * geometry on top of it. Called at the start of
	 * LoadProceduralScenario, once the incoming JSON is confirmed
	 * well-formed (so a malformed payload never wipes an already-loaded
	 * scenario).
	 */
	void ClearPreviousScenario();

	/**
	 * Applies the optional top-level "environment" object of a scenario
	 * payload to the current level: hides the engine template's terrain,
	 * retunes the sun, height fog and adds an unbound post-process volume
	 * (grade/exposure). Every field is optional; values are the ones
	 * measured in Epic's City Sample levels (see KNOWN_GAPS_AND_ISSUES.md).
	 * The post-process volume is tracked in SpawnedAssetActors so each
	 * LoadProceduralScenario call replaces it instead of stacking volumes.
	 */
	void ApplyEnvironment(const TSharedPtr<FJsonObject>& Environment);

	/**
	 * Spawns the optional top-level "lights" array of a scenario payload:
	 * one real point or spot light actor per entry (vehicle headlights and
	 * tail/brake lights, street lamps -- chosen by the Python side per
	 * time of day, so a daytime scenario simply carries none). Each entry
	 * is {"type": "point"|"spot", "position": [x, y, z] meters,
	 * "direction": [dx, dy, dz] (spot only), "color": [r, g, b] 0-1,
	 * "intensity": candela, "attenuation_m": radius, "inner_cone_deg",
	 * "outer_cone_deg" (spot only)}. Position and direction go through the
	 * same right-handed -> left-handed Y mirror as every other spawned
	 * asset. Spawned lights are tracked in SpawnedAssetActors, so each
	 * LoadProceduralScenario call replaces them. An entry missing a
	 * required field is skipped and counted, never fatal.
	 */
	void SpawnLights(const TArray<TSharedPtr<FJsonValue>>& LightsJson, int32& OutSpawned, int32& OutSkipped);

	/**
	 * Spawns the optional top-level "glows" array: one small unlit,
	 * additive emissive sphere per entry ({"position": [x, y, z] meters,
	 * "color": [r, g, b], "intensity", and either "radius_m" or an ellipsoid
	 * "semi_axes_m" [forward, lateral, vertical] with "rotation_rad"}) -- the visible glowing
	 * lens of a headlight or tail light (a light actor casts light but is
	 * itself invisible). Uses the project-owned /Game/VantageCV/M_EmissiveGlow
	 * (unreal_plugin/tools/create_glow_material.py) with its "GlowColor"
	 * parameter scaled by intensity, so it blooms. Tracked in
	 * SpawnedAssetActors like every other spawned actor.
	 */
	void SpawnGlows(const TArray<TSharedPtr<FJsonValue>>& GlowsJson, int32& OutSpawned, int32& OutSkipped);

	/**
	 * Hides ``Actor`` if its class looks like template terrain: Landscape
	 * proxies (the checkerboard/hills), the engine's plain StaticMeshActor,
	 * or a WorldPartitionHLOD merged distant-terrain proxy -- the last of
	 * which turned out to be the real cause of a pale "ribbon" artifact at
	 * the horizon that survived hiding the first two, see
	 * KNOWN_GAPS_AND_ISSUES.md. Returns true if ``Actor`` was hidden.
	 */
	static bool HideIfTemplateTerrain(AActor* Actor);

	/**
	 * FWorldDelegates::LevelAddedToWorld callback: hides every
	 * HideIfTemplateTerrain match in a level as it streams in. World
	 * Partition streams cells into the world via level-add, not
	 * UWorld::SpawnActor (confirmed live: binding FOnActorSpawned instead
	 * never fired for these actors, and the EngineSky dome kept showing
	 * up as a horizon "ribbon" no matter how the camera moved). This is
	 * the callback that actually fires for both the persistent level's
	 * initial load and every later World Partition cell.
	 */
	void OnLevelAddedToWorld(ULevel* Level, UWorld* World);

	/** Vehicles spawned by the most recent LoadProceduralScenario call
	 * (mesh sections are components of this actor and don't need
	 * separate tracking; spawned vehicles are independent actors in the
	 * world and do). */
	UPROPERTY()
	TArray<TObjectPtr<AActor>> SpawnedAssetActors;

	/**
	 * Guards registering OnLevelAddedToWorld with FWorldDelegates only
	 * once per world (it is a global static delegate shared by every
	 * world, so it must be checked, not just bound, on repeat
	 * LoadProceduralScenario calls) -- see that method's own comment.
	 */
	bool bRegisteredLevelAddedDelegate = false;

	// The map's own sun, sky, cloud and fog settings, captured the first time an
	// environment is applied and restored at the start of every scenario load, so
	// a scenario never inherits the previous one's lighting or weather.
	struct FMapEnvironmentDefaults
	{
		bool bCaptured = false;
		float SunIntensity = 0.0f;
		float SunTemperature = 6500.0f;
		bool bSunUseTemperature = false;
		FRotator SunRotation = FRotator::ZeroRotator;
		float SkyLightIntensity = 1.0f;
		float RayleighScale = 1.0f;
		float MieScale = 1.0f;
		float MieAbsorptionScale = 1.0f;
		float MieAnisotropy = 0.8f;
		float MultiScattering = 1.0f;
		float CloudLayerBottom = 0.0f;
		float CloudLayerHeight = 0.0f;
		// Every scalar parameter of the cloud material at capture time, restored on each load.
		TMap<FName, float> CloudScalars;
		float FogDensity = 0.0f;
		float FogHeightFalloff = 0.0f;
		float FogStartDistance = 0.0f;
		FLinearColor FogColor = FLinearColor::Black;
	};
	FMapEnvironmentDefaults MapDefaults;

	// Scalar parameter overrides per procedural-mesh material tag (for example
	// "asphalt"), set from the environment's "surface_scalars" and applied to each
	// generated mesh section of that tag as it is built (wet roads and pavement).
	// Cleared at the start of every load.
	TMap<FString, TMap<FName, float>> SurfaceScalars;

	// Scalar overrides keyed "<slot name or wildcard pattern>|<parameter>", applied to
	// every static-mesh material slot of every spawned asset (wet walls and cars).
	// Cleared at the start of every load.
	TMap<FString, float> AssetScalars;

	// Factors keyed "<slot pattern>|<colour parameter>": each matching slot's current colour
	// (its own value, a palette override or the material's default) is multiplied by the
	// factor. This is how wet walls and cars darken. Cleared at the start of every load.
	TMap<FString, float> AssetVectorScales;

	void ApplyAssetScalars(AActor* Actor) const;

	void CaptureMapEnvironmentDefaults();
	void RestoreMapEnvironmentDefaults();
};
