"""Real render triangles of the City Sample vehicle models, for occlusion tests.

The data file ``vehicle_meshes.npz`` is generated by ``bin/dump_vehicle_meshes.py``
from the running game: per model folder, ``<folder>_vertices`` (metres, vehicle
frame: +x forward, +y left, z up, origin at the placement point) and
``<folder>_triangles``. Body shell, wheels, doors and glass are included.
"""

from functools import lru_cache
from pathlib import Path
from typing import Optional, Tuple

import numpy as np
import numpy.typing as npt

from src.procedural.actor_placement import Vehicle

MESH_FILE = Path(__file__).with_name("vehicle_meshes.npz")


@lru_cache(maxsize=1)
def _archive() -> Optional[dict]:  # type: ignore[type-arg]
    """All arrays of the data file, or ``None`` if it has not been generated."""
    if not MESH_FILE.exists():
        return None
    with np.load(MESH_FILE) as data:
        return {name: data[name] for name in data.files}


def model_folder(asset_path: str) -> str:
    """The model folder name in a vehicle asset path (e.g. ``vehCar_vehicle02``)."""
    return asset_path.split("/")[3]


def model_mesh(folder: str) -> Optional[Tuple[npt.NDArray[np.float64], npt.NDArray[np.int64]]]:
    """(vertices, triangle indices) of a model in its own frame, or ``None`` if unknown."""
    archive = _archive()
    if archive is None or f"{folder}_vertices" not in archive:
        return None
    return (
        archive[f"{folder}_vertices"].astype(np.float64),
        archive[f"{folder}_triangles"].astype(np.int64),
    )


def world_triangles(vehicle: Vehicle) -> Optional[npt.NDArray[np.float64]]:
    """The vehicle's mesh placed in the world as a (T, 3, 3) triangle array, or ``None``.

    Applies the vehicle's heading about z and its placement point and surface height.
    """
    mesh = model_mesh(model_folder(vehicle.asset_path))
    if mesh is None:
        return None
    vertices, indices = mesh
    cos_h, sin_h = np.cos(vehicle.heading_rad), np.sin(vehicle.heading_rad)
    rotated = np.column_stack(
        [
            vertices[:, 0] * cos_h - vertices[:, 1] * sin_h,
            vertices[:, 0] * sin_h + vertices[:, 1] * cos_h,
            vertices[:, 2],
        ]
    )
    placed = rotated + np.array([vehicle.center[0], vehicle.center[1], vehicle.surface_z])
    return np.asarray(placed[indices])
