"""Real ground-truth box of every City Sample vehicle model, measured live.

GENERATED by ``bin/measure_vehicle_bounds.py`` -- do not edit by hand. Each
entry is (length, width, height, center_x, center_y, z_min) in metres in the
mesh's own frame (+X forward, origin at the mesh origin): the union of the
body, wheel and glass meshes (doors are excluded, they carry the mirrors,
and so is the interior frame, which overstates the big vehicles). The center
offset is where the box's center sits relative to the placement point."""

from typing import Dict, Tuple

VEHICLE_MODEL_BOUNDS: Dict[str, Tuple[float, float, float, float, float, float]] = {
    "vehCar_vehicle02": (4.789, 1.932, 1.752, -0.024, 0.0, 0.004),
    "vehCar_vehicle03": (5.4, 1.985, 1.54, -0.143, -0.0, -0.017),
    "vehCar_vehicle05": (4.525, 1.773, 1.703, 0.041, 0.0, 0.002),
    "vehCar_vehicle06": (4.367, 1.792, 1.375, 0.027, 0.0, 0.0),
    "vehCar_vehicle07": (4.41, 1.715, 1.428, -0.083, -0.0, 0.003),
    "vehCar_vehicle12": (5.4, 1.985, 1.927, -0.143, -0.0, -0.017),
    "vehCar_vehicle13": (5.52, 1.985, 1.843, -0.083, -0.0, -0.017),
    "vehVan_vehicle01": (4.791, 1.883, 1.852, -0.024, -0.0, 0.007),
    "vehVan_vehicle09": (6.392, 2.273, 2.458, 0.0, 0.0, 0.004),
    "vehTruck_vehicle04": (5.555, 1.993, 1.836, -0.223, 0.0, 0.002),
    "vehTruck_vehicle08": (6.217, 2.619, 3.165, 0.141, -0.0, 0.007),
    "vehTruck_vehicle11": (10.426, 3.471, 4.231, 0.008, -0.0, 0.008),
    "vehTruck_trailer01": (11.177, 2.589, 4.001, -6.152, -0.003, -0.004),
    "vehBus_vehicle10": (11.269, 2.811, 2.666, -0.035, 0.0, 0.002),
}
