"""Create the project-owned foliage materials and import the leaf texture.

Run once in a headless editor session (the game/editor must not be running):

    UnrealEditor-Cmd.exe <project>.uproject -d3d11 -nosplash -unattended -nullrhi
        -ExecutePythonScript=<this file>

Imports ``unreal_plugin/content/T_LeafCluster.png`` (generated by ``make_leaf_texture.py``) and
creates, in ``/Game/VantageCV/Foliage``:

- ``M_Foliage``: masked and two-sided; base colour = the texture's grey brightness times a ``Tint``
  vector parameter, opacity mask = the texture's alpha, matte.
- ``MI_Foliage_Spring``, ``MI_Foliage_Summer``, ``MI_Foliage_Fall``: differ in ``Tint``.
- ``M_Bark``: a plain matte brown.

The mesh tags ``foliage_*`` and ``bark`` resolve to them (``MaterialResolver.cpp``). Existing assets
are rebuilt, they are this project's own. Nothing shared is edited.
"""

import unreal  # type: ignore[import-not-found]  # pylint: disable=import-error

PACKAGE_PATH = "/Game/VantageCV/Foliage"
TEXTURE_FILE = r"F:/vscode/VantageCV-V2/unreal_plugin/content/T_LeafCluster.png"
LOG_PATH = r"F:/vscode/VantageCV-V2/unreal_plugin/tools/create_foliage_material.log"
# Linear colours multiplied with the leaf texture's brightness; calibrated against rendered frames
# (docs/experiments/32_*.md), not guessed.
TINTS = {
    "MI_Foliage_Spring": (0.40, 0.68, 0.33),
    "MI_Foliage_Summer": (0.32, 0.55, 0.32),
    "MI_Foliage_Fall": (0.75, 0.40, 0.08),
}
BARK_COLOUR = (0.05, 0.035, 0.025)
OUT = open(LOG_PATH, "w", encoding="utf-8")  # pylint: disable=consider-using-with


def say(*parts):
    """Write one line to the log file next to this script."""
    OUT.write(" ".join(str(part) for part in parts) + chr(10))
    OUT.flush()


def rebuild(name):
    """Delete an existing project asset so it is created fresh."""
    path = f"{PACKAGE_PATH}/{name}"
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        unreal.EditorAssetLibrary.delete_asset(path)


def import_texture():
    """Import the leaf PNG as a texture asset (sRGB, with alpha) and return it."""
    rebuild("T_LeafCluster")
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", TEXTURE_FILE)
    task.set_editor_property("destination_path", PACKAGE_PATH)
    task.set_editor_property("destination_name", "T_LeafCluster")
    task.set_editor_property("automated", True)
    task.set_editor_property("save", True)
    task.set_editor_property("replace_existing", True)
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
    texture = unreal.EditorAssetLibrary.load_asset(f"{PACKAGE_PATH}/T_LeafCluster")
    say("TEXTURE", texture)
    return texture


def create_foliage_material(texture):
    """The masked, two-sided parent material."""
    rebuild("M_Foliage")
    library = unreal.MaterialEditingLibrary
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    material = tools.create_asset(
        "M_Foliage", PACKAGE_PATH, unreal.Material, unreal.MaterialFactoryNew()
    )
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_MASKED)
    material.set_editor_property("two_sided", True)

    sample = library.create_material_expression(
        material, unreal.MaterialExpressionTextureSample, -800, 0
    )
    sample.set_editor_property("texture", texture)
    tint = library.create_material_expression(
        material, unreal.MaterialExpressionVectorParameter, -800, 300
    )
    tint.set_editor_property("parameter_name", "Tint")
    tint.set_editor_property("default_value", unreal.LinearColor(*TINTS["MI_Foliage_Summer"], 1.0))
    multiply = library.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -450, 100
    )
    library.connect_material_expressions(sample, "RGB", multiply, "A")
    library.connect_material_expressions(tint, "", multiply, "B")
    library.connect_material_property(multiply, "", unreal.MaterialProperty.MP_BASE_COLOR)
    library.connect_material_property(sample, "A", unreal.MaterialProperty.MP_OPACITY_MASK)
    roughness = library.create_material_expression(
        material, unreal.MaterialExpressionConstant, -450, 300
    )
    roughness.set_editor_property("r", 0.65)
    library.connect_material_property(roughness, "", unreal.MaterialProperty.MP_ROUGHNESS)
    library.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    say("MATERIAL", material.get_path_name())
    return material


def create_instances(parent):
    """One instance per season tint."""
    library = unreal.MaterialEditingLibrary
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    for name, colour in TINTS.items():
        rebuild(name)
        instance = tools.create_asset(
            name,
            PACKAGE_PATH,
            unreal.MaterialInstanceConstant,
            unreal.MaterialInstanceConstantFactoryNew(),
        )
        instance.set_editor_property("parent", parent)
        library.set_material_instance_vector_parameter_value(
            instance, "Tint", unreal.LinearColor(*colour, 1.0)
        )
        library.update_material_instance(instance)
        unreal.EditorAssetLibrary.save_loaded_asset(instance)
        say("INSTANCE", name, colour)


def create_bark():
    """A plain matte brown."""
    rebuild("M_Bark")
    library = unreal.MaterialEditingLibrary
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    material = tools.create_asset(
        "M_Bark", PACKAGE_PATH, unreal.Material, unreal.MaterialFactoryNew()
    )
    base = library.create_material_expression(
        material, unreal.MaterialExpressionConstant3Vector, -400, 0
    )
    base.set_editor_property("constant", unreal.LinearColor(*BARK_COLOUR, 1.0))
    library.connect_material_property(base, "", unreal.MaterialProperty.MP_BASE_COLOR)
    roughness = library.create_material_expression(
        material, unreal.MaterialExpressionConstant, -400, 200
    )
    roughness.set_editor_property("r", 0.9)
    library.connect_material_property(roughness, "", unreal.MaterialProperty.MP_ROUGHNESS)
    library.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    say("BARK", material.get_path_name())


def main():
    """Build every foliage asset, then quit the editor."""
    try:
        parent = create_foliage_material(import_texture())
        create_instances(parent)
        create_bark()
    except Exception as error:  # pylint: disable=broad-exception-caught
        say("ERROR", repr(error))
    say("DONE")
    unreal.SystemLibrary.execute_console_command(None, "QUIT_EDITOR")


main()
